from django.urls import path
from .views import (
    register, 
    login, 
    home, 
    student_dashboard, 
    employer_dashboard, 
    verify_email, 
    get_profile, 
    update_profile,
    get_employer_profile,
    update_employer_profile,
    view_student_profile, 
    post_listing,
    get_employer_listings,    
    delete_listing ,
    get_listing_detail,
    get_all_listings,
    save_job,
    unsave_job,
    get_saved_jobs,
    submit_application,
    propose_interview,
    get_student_interviews,
    get_employer_interviews,
    confirm_interview,
    decline_interview,
    get_employer_applications,
    get_admin_dashboard,
    admin_toggle_listing,
    update_application_status,
    get_student_notifications,
    mark_notification_read,
    get_employer_notifications,
    rate_cv,
)

urlpatterns = [
    path('', home),
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('student-dashboard/', student_dashboard),
    path('employer-dashboard/', employer_dashboard),
    path('verify-email/', verify_email),
    
    
    # Student profile
    path('student-profile/', get_profile, name='profile'),
    path('student-profile/update/', update_profile),
    path('view-student-profile/<str:username>/', view_student_profile),  
    
    # Employer profile
    path('employer-profile/', get_employer_profile),
    path('employer-profile/update/', update_employer_profile),

    path('post-listing/', post_listing),
    path('employer-listings/', get_employer_listings),         
    path('delete-listing/<str:listing_id>/', delete_listing), 
    path('listing/<str:listing_id>/', get_listing_detail),
    path('all-listings/', get_all_listings), 
    path('save-job/<str:listing_id>/', save_job),
    path('unsave-job/<str:listing_id>/', unsave_job),
    path('saved-jobs/', get_saved_jobs),
    path('apply/<str:listing_id>/', submit_application),
    path('interviews/propose/<str:application_id>/', propose_interview),
    path('interviews/student/', get_student_interviews),
    path('interviews/employer/', get_employer_interviews),
    path('interviews/<str:interview_id>/confirm/', confirm_interview),
    path('interviews/<str:interview_id>/decline/', decline_interview),
    path('employer-applications/', get_employer_applications),
    path('admin/dashboard/', get_admin_dashboard),
    path('admin/listing/<str:listing_id>/toggle/', admin_toggle_listing),
    path('application/<str:application_id>/status/', update_application_status),
    path('student-notifications/', get_student_notifications),
    path('notification/<str:notification_id>/read/', mark_notification_read),
    path('employer-notifications/', get_employer_notifications),
    path('rate-cv/', rate_cv),
]
